baseurl: https://valeriamorales-portfolio.netlify.app/
title: Valeria morales
image: Logo_Black.png
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: 'Valeria Morales 2021'
  description: Valeria Morales Portfolio
  email: vmorales.mam2022@london.edu
  formEmail: val.c.morales@gmail.com
  navlinks:
    - home: yes
      name: Portfolio
      url: portfolio/
    - name: About
      url: about/
    - name: Contact
      url: contact/
    - name: CV
      url: cv_vm.pdf
  sidebarAbout:
    - Masters in Management at London Business School | Bachelors of Science in Statistics from UCLA
    - Colombian, from Los Angeles, based in London
    - analytical, creative, & interested in tech
  social:
    email: vmorales.mam2022@london.edu
    github: https://github.com/valmoral
    instagram: https://www.instagram.com/valmoral37/
    linkedin: https://www.linkedin.com/in/valmoral37/
    spotify: https://open.spotify.com/user/222rmhm2cto6ki7yauqbnigoa
  style: default
