baseurl: https://valeriamorales-portfolio.netlify.app/
title: Valeria Morales
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: 'Valeria Morales 2021'
  description: Welcome to my portfolio
  email: vmorales.mam2022@london.edu
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - I am a Masters in Analytics Student at London Business School with a Bachelors of Science in Statistics and a passion for technology.
    - Colombian, from Los Angeles, based in London.
  social:
    email: vmorales.mam2022@london.edu
    github: https://github.com/valmoral
    instagram: https://www.instagram.com/valmoral37/
    linkedin: https://www.linkedin.com/in/valmoral37/
    spotify: https://open.spotify.com/user/222rmhm2cto6ki7yauqbnigoa
  style: default
